project_id = "qtyflfqbjftodchyyplz"

[functions.admin-grant-role-by-email]
verify_jwt = false

[functions.purva-chat]
verify_jwt = false

[functions.outbound-call]
verify_jwt = false

[functions.vapi-webhook]
verify_jwt = false

[functions.admin-notify]
verify_jwt = false
